[database]
engine = mysql
driver = pymysql
user = deep3576
port = 3306
password = Gmsshn!43
host = 127.0.0.1
#host = deep3576.mysql.pythonanywhere-services.com
name = deep3576$ProductionDB
charset = utf8mb4
FLASK_ENV=production
SECRET_KEY=change_this_to_a_very_random_long_value
# PythonAnywhere MySQL settings for user: deep3576, db: deep3576$ProductionDB
DB_USER=deep3576
DB_PASSWORD=Gmsshn!43
DB_HOST=deep3576.mysql.pythonanywhere-services.com
DB_NAME=deep3576$ProductionDB


[app]
# deployment environment label for your own reference
env = production
# Flask secret key
secret_key = change_this_to_a_very_random_long_value
# Branding
company_name = Kingsman Construction & Renovations Inc.
company_domain = kingsmanrenovations.ca
# Optional brand colors (used by templates)
primary_color = #0f172a
accent_color = #dc2626
logo_path = img/Kingsman_logo.png
favicon_path = img/favicon.ico




[ssh]
use_tunnel = true
ssh_host = ssh.pythonanywhere.com
ssh_port = 22
ssh_username = deep3576
# one of:
#ssh_pkey = ~/.ssh/id_rsa   # recommended
# or:
ssh_password = Gmsshn!43
remote_bind_port = 3306
